service: starwars-serverless-pt
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

custom: # serverless-prune-plugin
  prune:
    automatic: true
    number: 1

functions:
  hello:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get
