service: starwars-serverless-pt
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  # - serverless-plugin-typescript
  # - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-offline

custom: # serverless-prune-plugin
  prune:
    automatic: true
    number: 1

functions:

# endpoints swapi
  swapiResource:
    handler: build/functions/swapiResource/index.swapiResource
    events:
      - httpApi:
          path: /swapi/{resource}
          method: get
  swapiResourceId:
    handler: build/functions/swapiResourceId/index.swapiResourceId
    events:
      - httpApi:
          path: /swapi/{resource}/{id}
          method: get

# endpoints starships
  createStarships:
    handler: build/functions/createStarships/index.createStarships
    events:
      - httpApi:
          path: /starships
          method: post
  getStarships:
    handler: build/functions/getStarships/index.getStarships
    events:
      - httpApi:
          path: /starships
          method: get
  getStarship:
    handler: build/functions/getStarship/index.getStarship
    events:
      - httpApi:
          path: /starships/{id}
          method: get
  deleteStarship:
    handler: build/functions/deleteStarship/index.deleteStarship
    events:
      - httpApi:
          path: /starships/{id}
          method: delete
